project:
  type: book

book:
  title: "KGW Portfolio Notes"
  author: "Kevin G. Williams"
  date: "11/10/2025"
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/kwill1992/KGW_Portfolio_Notes.git  
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Part 1"
      chapters:
        - hexwall.qmd
    - part: "Part 2"
      chapters:
        - projects_hex.qmd    
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

